FROM docker/dev-environments-default:stable-1

RUN --mount=type=cache,target=/var/cache/apt \
 apt-get update && apt-get install -y \
 autoconf \
 bear \
 build-essential \
 cmake \
 libtool \
 python3-pip \
 python-is-python3

RUN pip install requests

ARG TOKEN

# RUN git clone https://${TOKEN:?err}@github.com/sstsimulator/sstcc.git

ENTRYPOINT ["sleep", "infinity"]
